#!/usr/bin/env python
#-*- coding:utf-8 -*-

import subprocess,sys
import psutil

#---------------------------

#---------------------------

#返回对应进程名的进程数
def s(name,vo):
 temp_back = 0
 time.sleep(1)
 for temp_proc in psutil.process_iter():
  if temp_proc.cmdline() != []:
  
   temp_js = 0
   temp_temp = ""
   while temp_js != len(temp_proc.cmdline()):
    temp_temp = temp_temp + str(temp_proc.cmdline()[temp_js]) + " "
    temp_js = temp_js + 1
   if temp_temp !="":
    temp_temp = temp_temp[:len(temp_temp)-1]
   #print "进程:'" + temp_temp + "'"
   if vo == True:
    if temp_temp.find(name)>-1:
     temp_back = temp_back +1
   else:
    if temp_temp == name:
     temp_back = temp_back +1
     
 #print "搜索:'" + name + "'"
 return temp_back
  
#返回所有进程名
def s_name():
 time.sleep(1)
 temp_psu = ""
 for temp_proc in psutil.process_iter():
  if temp_proc.cmdline() != []:
   temp_js = 0
   while temp_js != len(temp_proc.cmdline()):
    temp_psu = temp_psu + " " + str(temp_proc.cmdline()[js])
    temp_js = temp_js + 1
   temp_psu = temp_psu + "\r\n"
 if temp_psu != "":
  return temp_psu[:len(temp_psu)-1]
 else:
  return temp_psu

if __name__ == "__main__":
 
 temp_x = 0
 order = ""
 while temp_x != len(sys.argv):
  if temp_x +1 == len(sys.argv):
   order = order + sys.argv[temp_x]
  else:
   order = order + sys.argv[temp_x] + " "
  temp_x = temp_x + 1

 temp_x1 = 1
 if order.find("-read ") >-1:
  temp_x1 = int(order[order.find("-read ")+6:order.find(" ",order.find("-read ")+6)])
 
 if order.find("-order ") >-1:
  order = order[order.find("-order ")+7:]
 else:
  order =""
 
 if order == "":
  exit()

 temp_x = 0
 if order != "":
  while temp_x != temp_x1:
   subprocess.Popen(order,shell=True)
   temp_x = temp_x +1
 
 print "%information"
 print "order:'" + order + "'"
 print "read:'" + str(temp_x1) + "'"
 print "%"
 exit()
