#!/usr/bin/env python
#-*- coding:utf-8 -*-

import subprocess,sys

if __name__ == "__main__":
 
 x = 0
 order = ""
 while x != len(sys.argv):
  order = order + sys.argv[x] + " "
  x = x + 1

 x1= 1
 if order.find("-read ") >0:
  x1 = int(order[order.find("-read ")+6:order.find(" ",order.find("-read ")+6)])
 
 if order.find("-order ") >0:
  order = order[order.find("-order ")+7:]
 else:
  order =""
 
 if order == "":
  exit()

 print "%"
 print order
 print x1
 print "%"

 x = 0
 
 if order != "":
  while x != x1:
   subprocess.Popen(order,shell=True)
   x =x +1
 exit()
